version: '3.8'
services:
  auth-db:
    container_name: auth-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data: